version: "3.7"
services:
  sparkmaster:
    image: sparkcontainer/first:v2
    container_name: sparkmaster
    ports:
      - "8080:8080"
      - "7077:7077"
    command:
      - "$SPARK_HOME/sbin/start-master.sh"
  spark-worker-1:
    image: sparkcontainer/first:v2
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    command: "$SPARK_HOME/sbin/start-worker.sh ${SPARK_MASTER}"
  spark-worker-2:
    image: sparkcontainer/first:v2
    container_name: spark-worker-2
    ports:
      - "8082:8082"
    command: "$SPARK_HOME/sbin/start-worker.sh ${SPARK_MASTER}"
